### ISSUE TITLE
Standalone version using vrp modules

### ISSUE THREAD

**Issue by chopo156** [Wick89/Wk_fire#2]
Hi, i download this version but in the __resources.lua is a "dependency "vrp" that cause the script not to load.

**Comment by Wick89** [comment]
My bad, 
DELETE it
dependency "vrp"

server_scripts {
	"@vrp/lib/utils.lua", - - it one
}
client_scripts { 
	"lib/Tunnel.lua", - - it two
	"lib/Proxy.lua", - - -

**Comment by chopo156** [comment]
thanks!!!
